# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnRXSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRXSwift
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'LearnRXSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnRXSwiftUITests' do
    # Pods for testing
  end

end
